MAP_MAPPING = {
    ["34"] = {"DK Isles", "DK Isles"},
    ["189"] = {"DK Isles", "DK Isles"}, --BFI
    ["169"] = {"DK Isles", "Japes Lobby"},
    ["173"] = {"DK Isles", "Aztec Lobby"},
    ["195"] = {"DK Isles", "Snide's Room"},
    ["175"] = {"DK Isles", "Factory Lobby"},
    ["174"] = {"DK Isles", "Galleon Lobby"},
    ["178"] = {"DK Isles", "Forest Lobby"},
    ["194"] = {"DK Isles", "Caves Lobby"},
    ["193"] = {"DK Isles", "Castle Lobby"},
    ["170"] = {"DK Isles", "Helm Lobby"},
    ["176"] = {"DK Isles", "Training Grounds"},
    ["171"] = {"DK Isles", "Training Grounds"}, -- Treehouse
    ["97"] = {"DK Isles", "DK Isles"}, --Prison
    ["7"] = {"Jungle Japes", "Main Area"},
    ["12"] = {"Jungle Japes", "Main Area"}, -- Beehive
    ["13"] = {"Jungle Japes", "Main Area"}, --Painting Room
    ["4"] = {"Jungle Japes", "Main Area"}, --Diddy Mountain
    ["6"] = {"Jungle Japes", "Main Area"}, --Japes Minecart
    ["33"] = {"Jungle Japes", "Japes Underground"},
    ["37"] = {"Jungle Japes", "Jungle Japes"}, --Blast Course
    ["38"] = {"Angry Aztec", "Main Area"},
    ["16"] = {"Angry Aztec", "Tiny Temple"},
    ["19"] = {"Angry Aztec", "Main Area"}, -- DK 5DT
    ["21"] = {"Angry Aztec", "Main Area"}, -- Diddy 5DT
    ["23"] = {"Angry Aztec", "Main Area"}, --Lanky 5DT
    ["22"] = {"Angry Aztec", "Main Area"}, --Tiny 5DT
    ["24"] = {"Angry Aztec", "Main Area"}, --Chunky 5DT
    ["14"] = {"Angry Aztec", "Main Area"}, -- Beetle Race
    ["20"] = {"Angry Aztec", "Llama Temple"},
    ["41"] = {"Angry Aztec", "Main Area"}, -- Blast Course
    ["26"] = {"Frantic Factory", "Main Area"},
    ["27"] = {"Frantic Factory", "Main Area"},-- Car Race
    ["29"] = {"Frantic Factory", "Main Area"}, --Power Hut
    ["36"] = {"Frantic Factory", "Main Area"}, -- Crusher
    ["110"] = {"Frantic Factory", "Main Area"}, -- Blast Course
    ["30"] = {"Gloomy Galleon", "Main Area"},
    ["49"] = {"Gloomy Galleon", "Main Area"}, -- Lighthouse
    ["45"] = {"Gloomy Galleon", "Main Area"}, -- Mermaid
    ["31"] = {"Gloomy Galleon", "Main Area"}, -- Sickbay
    ["39"] = {"Gloomy Galleon", "Main Area"}, -- Seal Race
    ["44"] = {"Gloomy Galleon", "Main Area"}, -- Treasure Chest
    ["179"] = {"Gloomy Galleon", "Main Area"}, -- Sub
    ["51"] = {"Gloomy Galleon", "Main Area"}, -- Mechfish
    ["46"] = {"Gloomy Galleon", "Main Area"}, -- DK/Tiny 5DS
    ["43"] = {"Gloomy Galleon", "Main Area"}, -- Diddy/Lanky/Chunky 5DS
    ["47"] = {"Gloomy Galleon", "Main Area"}, -- 2DS
    ["54"] = {"Gloomy Galleon", "Main Area"}, -- Blast Course
    ["48"] = {"Fungi Forest", "Main Area"},
    ["55"] = {"Fungi Forest", "Main Area"}, -- Chunky Minecart
    ["64"] = {"Fungi Forest", "Main Area"}, -- Giant Mushroom
    ["71"] = {"Fungi Forest", "Main Area"}, -- Face Puzzle
    ["70"] = {"Fungi Forest", "Main Area"}, -- Zinger Room
    ["63"] = {"Fungi Forest", "Main Area"}, -- Mushroom Bounce
    ["52"] = {"Fungi Forest", "Main Area"}, -- Anthill
    ["61"] = {"Fungi Forest", "Front Mill"},
    ["62"] = {"Fungi Forest", "Rear Mill"},
    ["60"] = {"Fungi Forest", "Rear Mill"}, -- Spider Boss
    ["56"] = {"Fungi Forest", "Main Area"}, -- Rafters
    ["57"] = {"Fungi Forest", "Main Area"}, -- Winch
    ["58"] = {"Fungi Forest", "Main Area"}, -- Mill Attic
    ["59"] = {"Fungi Forest", "Barn"},
    ["188"] = {"Fungi Forest", "Main Area"}, -- Blast Course
    ["72"] = {"Crystal Caves", "Main Area"},
    ["82"] = {"Crystal Caves", "Main Area"},
    ["98"] = {"Crystal Caves", "Main Area"},
    ["86"] = {"Crystal Caves", "Main Area"},
    ["100"] = {"Crystal Caves", "Main Area"},
    ["85"] = {"Crystal Caves", "Main Area"},
    ["84"] = {"Crystal Caves", "Main Area"},
    ["95"] = {"Crystal Caves", "Main Area"},
    ["89"] = {"Crystal Caves", "Main Area"},
    ["91"] = {"Crystal Caves", "Main Area"},
    ["92"] = {"Crystal Caves", "Main Area"},
    ["200"] = {"Crystal Caves", "Main Area"},
    ["94"] = {"Crystal Caves", "Main Area"},
    ["93"] = {"Crystal Caves", "Main Area"},
    ["90"] = {"Crystal Caves", "Main Area"},
    ["186"] = {"Crystal Caves", "Main Area"},
    ["87"] = {"Creepy Castle", "Exterior"},
    ["164"] = {"Creepy Castle", "Exterior"}, -- Tree
    ["114"] = {"Creepy Castle", "Exterior"}, -- Library
    ["88"] = {"Creepy Castle", "Ballroom"},
    ["113"] = {"Creepy Castle", "Museum"},
    ["185"] = {"Creepy Castle", "Museum"}, -- Car Race
    ["105"] = {"Creepy Castle", "Exterior"}, -- Tower
    ["168"] = {"Creepy Castle", "Exterior"}, -- Greenhouse
    ["167"] = {"Creepy Castle", "Exterior"}, -- Trash
    ["166"] = {"Creepy Castle", "Exterior"}, -- Shed
    ["183"] = {"Creepy Castle", "Crypt Hub"},
    ["112"] = {"Creepy Castle", "DK - Diddy - Chunky Crypt"},
    ["106"] = {"Creepy Castle", "DK - Diddy - Chunky Crypt"}, -- Minecart
    ["108"] = {"Creepy Castle", "Crypt Hub"}, -- Mausoleum
    ["151"] = {"Creepy Castle", "Dungeon Tunnel"},
    ["163"] = {"Creepy Castle", "DK - Diddy - Lanky Dungeon"},
    ["187"] = {"Creepy Castle", "Exterior"}, -- Blast Course
    ["17"] = {"Hideout Helm", "Hideout Helm"},
    ["203"] = {"DK Isles", "DK Isles"}, -- DK Phase
    ["204"] = {"DK Isles", "DK Isles"}, -- Diddy Phase
    ["205"] = {"DK Isles", "DK Isles"}, -- Lanky Phase
    ["206"] = {"DK Isles", "DK Isles"}, -- Tiny Phase
    ["207"] = {"DK Isles", "DK Isles"}, -- Chunky Phase
    ["214"] = {"DK Isles", "DK Isles"}, --  toes.txt
}